
title: Roger's homepage
description: Ingénieur développeur & harmoniciste amateur, Sur Terre, nous naissons tous égaux mais certains sont plus égaux que d'autres.
author: Roger Srey
email: roger_srey@hotmail.com
github_username:  srroger
show_downloads: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
# theme: jekyll-theme-primer
# SRRTEST remote_theme: pages-themes/architect@v0.2.0
remote_theme: pages-themes/primer
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true # Auto-generate ID's for headings
plugins:
  - jekyll-remote-theme # https://github.com/benbalter/jekyll-remote-theme
  - jekyll-default-layout # https://github.com/benbalter/jekyll-default-layout
  - jekyll-default-layout # https://github.com/benbalter/jekyll-titles-from-headings
  - jekyll-relative-links # https://github.com/benbalter/jekyll-relative-links
  - jekyll-avatar # https://github.com/benbalter/jekyll-avatar
sass:
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - node_modules/
