theme: jekyll-theme-minimal
title: Roger's homepage
description: Ingénieur développeur & harmoniciste amateur, Sur Terre, nous naissons tous égaux mais certains sont plus égaux que d'autres.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
